### ISSUE TITLE
[Q1] Roadmap

### ISSUE THREAD

**Issue by ArlonAntonius** [tenancy/tenancy#18]
# Roadmap

## Organisation
- [X] Create Roadmap Draft
- [x] Maintain roadmap
- [x] Discuss Hyn/Multi-Tenant Migration
- [x] Consider renaming of Tenancy / Tenancy and Tenancy / Framework
- [x] Check advantages of disabling auto discovery

## [Tenancy / Tenancy](https://github.com/tenancy/framework)
- [x] Start work on Beta Release
- [x] Add Caching #20 
- [x] Code Coverage to 70+%
- [x] Tenant Disk Package #19 
- [x] Tenant Config Package #2 

## [Tenancy / Docs](https://github.com/tenancy/docs)
- [x] Start Documentation on Tenancy Beta Release

**Comment by luceos** [comment]
We need to decide whether we're replacing t/t with t/f and if so, what to name the current t/t repo as it holds the core functionality.

Laravel has laravel/framework which contains all illuminate packages, with illuminate/foundation being the "core" functionality.

**Comment by luceos** [comment]
Another discussion would be whether to hold on to package auto discovery (current situation) or that we will obligate manual service provider registration. This seems to have caused some issues in the past with h/m.

**Comment by ArlonAntonius** [comment]
@luceos Please specify what issues you're referring to.
We can't discuss such a thing without knowing the exact issues it might cause.

**Comment by luceos** [comment]
Those comments are a reminder that we need to tackle that. Discussing all that in this issue would clutter the issue too much. Maybe add them on the quarterly and/or create separate issues for them. Sorry to spam them, I'm trying to structure some thoughts.

**Comment by d8vjork** [comment]
Any plan of provide some examples in docs for integrate this with Docker?

**Comment by luceos** [comment]
@d8vjork 

You can use the identification driver environment, the documentation currently can't show that document, but this is it: https://github.com/tenancy/docs/blob/master/docs/tenancy/1.x/identification-driver-environment.md

**Comment by luceos** [comment]
Successive item #42
