### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ArlonAntonius** [tenancy/tenancy#42]
# Roadmap
### Note
We're still adding things that need to be done to the roadmap. Every task still needs their own issue, we will get to all of that once we have the feeling that all the tasks are listed here.

## Organisation
- [ ] Create a Governance Document (Arlon & Daniel)
- [x] Consider renaming Bridge (Hyn-Multi-Tenant-Bridge to Multi-Tenant-Bridge)
- [ ] Talk about the release strategy

## [Tenancy / Tenancy](https://github.com/tenancy/framework)
- [x] Consider getting rid of (most of) the config files
- [x] Restructure Configs so the are under a Tenancy Folder in the Config folder.
- [ ] Check full Queue Works [Due to current Multi-Tenant issue] (#46)
- [x] Increase Code Coverage to 80%+
- [x] Affects Migrating / Seeding (#47)
- [x] Separated Driver / Package Tests
- [x] Database Driver Tests
- [x] Look at how 3rd party packages should integrate
- [x] Look at all 3rd party tools we use and set them up correctly
- [x] Remove SQLite Config Need
- [x] Make Database Tests Abstract

## [Tenancy / Docs](https://github.com/tenancy/docs)
- [ ] Document Full Installation of package(s)
- [x] Document General Affects Approach
- [ ] Document Database Driver Creation

## [Tenancy / Bridge](https://github.com/tenancy/multi-tenant-bridge)
- [ ] Discuss what still needs to be done (Finding a current multi-tenant project to migrate)

**Comment by luceos** [comment]
- Renaming the bridge, ok with that. Will do so unless someone beats me to it.
- What are your ideas about the package/driver tests exactly? Do you want to include test classes in the testing package for (third party) driver testing?
- Documentation on the Affects Approach, I recently wrote [this](https://laravel-tenancy.com/docs/tenancy/1.x/affects), does that suffice?
- All items, as far as their scope is more than a few minutes work, do require their own issue.

Thanks, let's execute these as soon as possible.

**Comment by ArlonAntonius** [comment]
- Renamed the bridge, cause I'm a baller 💯 
- What I meant was having separate tests on each package that tests their complete functionality and that CircleCI would test it. Especially for db drivers as you might not want to test those on your machine at home.
EDIT: We could then exclude DB tests from the T/T main test suite
- This piece of documentation seems ok for now.
- Own issues will come later on when I'm sure we are not missing anything

**Comment by ArlonAntonius** [comment]
We achieved most things, new roadmap WIP.
