### ISSUE TITLE
Roadmap To Release

### ISSUE THREAD

**Issue by ArlonAntonius** [tenancy/tenancy#97]
## Tenancy Organisation
- [x] Continue work on Governance Document
- [x] Create Support Policy
- [x] Discuss Support Policy Internally

## Tenancy Site
- [x] Spotlight Placeholder
- [x] Consultancy Page

## Tenancy / Tenancy
- [x] Ask Community for Feedback / what they want
- [x] Go over all Composer Dependencies
- [x] Consider renaming all Affects / Hooks for consistency
- [x] Laravel 6 Compatibility
- [x] Discuss where to place Password Providing
- [x] Discuss Third Party Integration (previously AffectsModels)
- [x] Remove Repository Templates
- [x] TenantAwareJob RFC (Trait vs current solution)
- [x] Fix CircleCI Caching
- [x] Ask backers for feedback
- [x] Add AffectsMail
- [x] Identify Performance Improvements
- [x] Discuss VHost Generations
- [x] Have a look at Queue Identification
- [x] Have a look at Affects Connections, implementation seems odd

## Tenancy / Multi Tenant
- [x] Fix Multi-Tenant CircleCI Tests
- [x] Laravel 6 Compatibility?

## Tenancy / Docs
- [ ] Document all packages
- [ ] Document Affects Creation
- [ ] Document Database Driver Creation
- [ ] Document Hooks Creation

## Others
- [x] Talk about integrations with Laravel Eco System

**Comment by fridzema** [comment]
Are there people that use this package already? 
Is it recommended to start with this package now or with the old one?

**Comment by ArlonAntonius** [comment]
@fridzema I really appreciate your interest in Tenancy.

## Are people already using it?
Yes, there are people already using this package. Some of them use it to learn the new way of doing tenancy and some in order to have it implemented for when we actually release it.
I myself already installed it in quite some projects, but those are not running in production yet.

## Which tenancy package should I use?
Short answer: Multi-Tenant has been battle-tested and proven to work over the years. Tenancy has not been released yet so some structure changes might still happen.
Long answer: [Probably best to read luceos' post on our forums.](https://discuss.tenancy.dev/d/3-is-it-okay-to-use-tenancy-tenancy-already)

**Comment by alexander-rieder** [comment]
So when will this package get released?

**Comment by ArlonAntonius** [comment]
Hi @alexander-rieder,

I'm glad to hear you're interested in our new package.
We're still working on the package and don't have an ETA yet.

I can highly recommend you to follow us on our channels so you can stay up-to-date about the latest news.
 - [Discord](https://tenancy.dev/chat)
 - [Github](https://github.com/tenancy)
- [Site](https://tenancy.dev/)

**Comment by bkintanar** [comment]
Looking forward for the date 1.0 gets released!

**Comment by ArlonAntonius** [comment]
We tagged 1.0
